<?php

/**
 * Theme hook
 */
function gestion_usuario_theme($existing, $type, $theme, $path) {
     
    return array(
        'lista_usuarios' => array(
                                'variables' => array(
                                    'titulo' => 'Título por defecto',
                                    'descripcion' => 'descripción por defecto',
                                    'usuarios'   => NULL
                                    ),
                                'template' => 'lista_usuarios'
        )
    );
}


